language: python

cache: pip

os:
  - linux

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy2.7-5.10.0
  - pypy3.5

env:
  - NUMPY="numpy==1.13.1"
  - NUMPY="numpy==1.14.5"
  - NUMPY="numpy>=1.15"

matrix:
  exclude:
    - python: pypy2.7-5.10.0
      env: NUMPY="numpy==1.14.5"
    - python: pypy3.5
      env: NUMPY="numpy==1.14.5"
    - python: pypy2.7-5.10.0
      env: NUMPY="numpy==1.13.1"
    - python: pypy3.5
      env: NUMPY="numpy==1.13.1"

install:
  - env
  - echo $TRAVIS_PYTHON_VERSION
  - pip install --upgrade setuptools_scm
  - pip install $NUMPY
  - python -c 'import numpy; print(numpy.__version__)'
  - pip install awkward
  - python -c 'import awkward; print(awkward.__version__)'
  - pip install "uproot-methods>=0.2.0"
  - python -c 'import uproot_methods; print(uproot_methods.__version__)'
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]] ; then pip install pandas ; fi

addons:
  apt:
    packages:
      - python-setuptools

script:
  python setup.py test

notifications:
  slack: scikit-hep:b6cgBXwccPoaCNLn5VKFJFVy

deploy:
  provider: pypi
  user: pivarski
  password:
    secure: "BpSLpIcnkTtey4MILj0hiBPCF2W89iAyPbMs4eGO+KMYrACbuXoSR5Pt+Fm4JZpBF5apQeW2ul3WZLpJYNCnkZ/FnliUJwmfJVzcSJrJBmG0dkYyGtASaxuIR7BK4GWuMC00YVcqUX33mExwodU+P54LzXsFYIM4uVjjZgUWrlMxgZTPrYmfSowQfSAxkSV9TUSPZoh8ofONBUZJrt0dzeO8MnIfbssMnI2VMnWv3FG9H0eWxbzaWLjQBOQmMHRXPqGWBflwJ5uUsdBEFKoDpbj9JhDesiULcxezHHFxnWeXr0z7lR6KGM+R3rSwjCrLrS/0MQnXmW8+00pNVLwxjGOYrbSinnvBdZ+Olwb8PcGnqXVFAf0EdwWsYgrX2055vzJDpH0d82t3CAu2RrvpStq/TuDydCfPHmehIpJwBbicKAOmK+DIcMKs/rqpGnb4TCFav0L+zB+xQBqn5tZhbev6F0fPtyuUbrjCPqpb/HikzaZoSnqKA39FSK3wBDP3K13GkEJZiYlq0lvynQD5Ye/1DB9OKH3Vdzohi0JStopAtEga5YvH/CzpIm3D9gK7ZpIVKLXf79ebxAMeYGBNFxEI9SKLdWgxL0kJoCxyZWxdzusyafxWRLp76xJ5mMMNEb+RgNXThgybVBISWhD+WjhOodUm/43sty5eMM4mKRs="
  distributions: "sdist bdist_wheel --universal"
  on:
    tags: true
    branch: master
    condition: '$TRAVIS_PYTHON_VERSION = "3.6" && $NUMPY = "numpy>=1.15"'

stages:
  - test
  - name: docs
    if: (branch = master) AND (NOT (type IN (pull_request)))

jobs:
  include:
  - stage: docs
    python: '3.6'
    env: NUMPY="numpy>=1.15"
    addons:
      chrome: stable
      apt:
        packages:
          - chromium-chromedriver
    before_install:
      - sudo apt-get update
      - sudo apt-get -qq install pandoc
      - pip install --upgrade pip setuptools wheel
      - pip install selenium
    install:
      - pip install -U -q .
    before_script:
      - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
    script:
    # Open Binder example in browser to trigger repo2docker to build image
    - python binder/trigger_binder.py --url https://mybinder.org/v2/gh/scikit-hep/uproot/master
    - python binder/trigger_binder.py --url https://mybinder.org/v2/gh/scikit-hep/uproot/master?filepath=binder%2Ftutorial.ipynb
    - python binder/trigger_binder.py --url https://mybinder.org/v2/gh/scikit-hep/uproot/master?filepath=binder%2Fversion-3-features.ipynb
